Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive)
    Default: 'ItemFinder'
    Type: String
  RepositoryName:
    Description: Name of GitHub repository (case sensitive)
    Default: '*'
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ''
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: 'sts.amazonaws.com'
    Type: String

Conditions:
  CreateOIDCProvider:
    Fn::Equals:
      - !Ref OIDCProviderArn
      - ''

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-action-deploy-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                Fn::If:
                  - CreateOIDCProvider
                  - !Ref GithubOidc
                  - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff

Outputs:
  Role:
    Value: !GetAtt Role.Arn
