name: 3.0.0 Cognito

on:
  workflow_dispatch:

jobs:
  setup-cognito:
    permissions:
      id-token: write
      contents: read
      packages: read
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-deploy-role
          aws-region: eu-north-1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy cognito stack
        run: |
          pnpm dlx cdk deploy --app "npx ts-node bin/foundation.ts" cognito-stack \
          --require-approval never
